[package]
name = "tremor-sys"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
libc = "*"
ogg-sys = "*"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"
